{
 "title": "GraphQL",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "GraphQL Execute Duration Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(graphql_execute_duration_milliseconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GraphQL Execute Duration RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(graphql_execute_duration_milliseconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GraphQL Resolve Duration Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(graphql_resolve_duration_milliseconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GraphQL Resolve Duration RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(graphql_resolve_duration_milliseconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}